/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as SelectComboboxRouteImport } from './routes/select-combobox'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TableRouteImport } from './routes/table'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsComponentIdRouteImport } from './routes/components/$componentId'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopProductProductIdRouteImport } from './routes/shop/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectComboboxRoute = SelectComboboxRouteImport.update({
  id: '/select-combobox',
  path: '/select-combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsComponentIdRoute = ComponentsComponentIdRouteImport.update({
  id: '/$componentId',
  path: '/$componentId',
  getParentRoute: () => ComponentsRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductProductIdRoute = ShopProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/select-combobox': typeof SelectComboboxRoute
  '/shop': typeof ShopRouteWithChildren
  '/table': typeof TableRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/components/': typeof ComponentsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-combobox': typeof SelectComboboxRoute
  '/table': typeof TableRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/components': typeof ComponentsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteWithChildren
  '/select-combobox': typeof SelectComboboxRoute
  '/shop': typeof ShopRouteWithChildren
  '/table': typeof TableRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/shop/cart': typeof ShopCartRoute
  '/components/': typeof ComponentsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/product/$productId': typeof ShopProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/select-combobox'
    | '/shop'
    | '/table'
    | '/components/$componentId'
    | '/shop/cart'
    | '/components/'
    | '/shop/'
    | '/shop/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-combobox'
    | '/table'
    | '/components/$componentId'
    | '/shop/cart'
    | '/components'
    | '/shop'
    | '/shop/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/select-combobox'
    | '/shop'
    | '/table'
    | '/components/$componentId'
    | '/shop/cart'
    | '/components/'
    | '/shop/'
    | '/shop/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  SelectComboboxRoute: typeof SelectComboboxRoute
  ShopRoute: typeof ShopRouteWithChildren
  TableRoute: typeof TableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-combobox': {
      id: '/select-combobox'
      path: '/select-combobox'
      fullPath: '/select-combobox'
      preLoaderRoute: typeof SelectComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/$componentId': {
      id: '/components/$componentId'
      path: '/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ComponentsComponentIdRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/product/$productId': {
      id: '/shop/product/$productId'
      path: '/product/$productId'
      fullPath: '/shop/product/$productId'
      preLoaderRoute: typeof ShopProductProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsComponentIdRoute: typeof ComponentsComponentIdRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsComponentIdRoute: ComponentsComponentIdRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductProductIdRoute: typeof ShopProductProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductProductIdRoute: ShopProductProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  SelectComboboxRoute: SelectComboboxRoute,
  ShopRoute: ShopRouteWithChildren,
  TableRoute: TableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
